apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-02-app-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev-02
  source:
    repoURL: https://github.com/grantking/argocd.git
    targetRevision: dev-02
    path: apps
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev-02

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
