apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-01-app-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev-01
  source:
    repoURL: https://github.com/grantking/argocd.git
    targetRevision: dev-01
    path: apps
    helm:
      parameters:
        - name: "thisisatest"
          value: "testtest"

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-01

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

