apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postman-app-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/grantking/argocd.git
    targetRevision: crossplane
    path: apps
    helm:
      parameters:
        - name: "pm.namespace"
          value: "postman"

  destination:
    server: https://kubernetes.default.svc
    namespace: postman-crossplane

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

