apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grantking-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/grantking/argocd.git
    targetRevision: HEAD
    path: apps
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
