apiVersion: v2
name: postman-platform
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

appVersion: "1.0"

dependencies:
  - name: configservice
    version: "0.4.1"
    repository: "http://3.18.175.109:8080"

  - name: prometheus-community/kube-prometheus-stack
    version: "48.3.1"
    repository: "https://prometheus-community.github.io/helm-charts"

  - name: kube-ops/grafana
    version: "1.0.2"
    repository: "https://charts.kube-ops.io"