# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

petstore:
   replicaCount: 2
   container:
      limits:
         cpu: "1"
         memory: "1G"
      requests:
         cpu: "1"
         memory: "1G"