# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configservice:
   replicaCount: 1

grafana:
   adminPassword: admin
   datasources:
      datasources.yaml:
         apiVersion: 1
         datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://prometheus-server.prometheus.svc.cluster.local
              isDefault: true