# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

petstore:
   replicaCount: 2

mysql:
   persistence:
      enabled: false
   mysqlRootPassword: welcome123