apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postman-data
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: postman-data
    server: https://kubernetes.default.svc
  project: default
  source:
    path: postman-data
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
