# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mysql:
   fullnameOverride: shared-mysql
   persistence:
      enabled: false
   auth:
      rootPassword: welcome123
   primary:
      livenessProbe:
         enabled: true